name: Changelog Reminder
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main
  push:
    branches:
      - "improve-changelog"

jobs:
  build:
    name: Check Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@9328bab880abf4acc377d77718d28c6ac167f154 # v35.7.2
        with:
          files_ignore: |
            .github/workflows/*
            **/**.md

      - name: List all files
        run: |
            echo "${{ steps.changed-files.outputs.any_changed }}"
            echo "${{ steps.changed-files.outputs.any_deleted }}"
            echo "${{ steps.changed-files.outputs.any_modified }}"

      - name: Changelog check
        if: |
          steps.changed-files.outputs.any_changed == 'true' &&
          steps.changed-files.outputs.any_deleted == 'true' &&
          steps.changed-files.outputs.any_modified == 'true'
        uses: Zomzog/changelog-checker@v1.3.0
        with:
          fileName: CHANGELOG.md
          noChangelogLabel: A:no-changelog
          checkNotification: Simple
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
